name: "xinference_standalone_gpu"
services:

  xinference:
    image: xprobe/xinference:v0.12.3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              driver: nvidia
              count: all
    environment:
      - XINFERENCE_MODEL_SRC=modelscope
    volumes:
      - /data/llmops/models:/data/llmops/models
      - ./xinference:/root/.xinference
    ports:
      - 9998:9997
    command: xinference-local -H 0.0.0.0 --log-level debug
    healthcheck:
      test: curl --fail http://localhost:9997/status || exit 1
      interval: 20s
      timeout: 5s
      retries: 6
      start_period: 15s

