name: "xinference_standalone"
services:
    xinference_standalone:
        image: xprobe/xinference:v0.11.3-cpu
        ports:
            - 9997:9997
        command:  xinference-local -H 0.0.0.0 --log-level debug
        volumes:
            - /data/llmops/models:/data/llmops/models
            - /your_home/.xinference:/root/.xinference
        healthcheck:
            test: curl --fail http://localhost:9997/status || exit 1
            interval: 20s
            timeout: 5s
            retries: 6
            start_period: 15s
