name: "xinference_cluster_gpu"

services:
  xinference: &xinference
    image: xprobe/xinference:v0.12.3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              driver: nvidia
              count: all
    environment:
      - XINFERENCE_MODEL_SRC=modelscope
    volumes:
      - /data/llmops/models:/data/llmops/models
      - ./xinference:/root/.xinference
    networks:
      - net

  xinference_supervisor:
    <<: *xinference
    ports:
      - 9998:9997
    command: xinference-supervisor -H xinference_supervisor --log-level debug
    healthcheck:
      test: curl --fail http://xinference_supervisor:9997/status || exit 1
      interval: 20s
      timeout: 5s
      retries: 6
      start_period: 15s

  xinference_worker_01:
    depends_on:
      xinference_supervisor:
        condition: service_healthy
    <<: *xinference
    command: xinference-worker -H xinference_worker_01 -e "http://xinference_supervisor:9997" --log-level debug

  xinference_worker_02:
    depends_on:
      xinference_supervisor:
        condition: service_healthy
    <<: *xinference
    command: xinference-worker -H xinference_worker_02 -e "http://xinference_supervisor:9997" --log-level debug

networks:
  net:
